# This query returns groups of asylum seekers who have a specific nationality ( in the specific example Soedanees ).
# Nationalities have to be in dutch
#+ endpoint: http://stardog.clariah-sdh.eculture.labs.vu.nl/test#!/query

﻿prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX trumpvoc: <http://localhost:5820/test/vocab/>
PREFIX trumpres: <http://localhost:5820/test/resources/>

select distinct ?asylum_seekers ?nationality ?label ?value ?date ?country
where { 
	?asylum_seekers a trumpvoc:Asylum_seekers .
  	?asylum_seekers trumpvoc:nationality ?nationality .
  	?asylum_seekers trumpvoc:value ?value .
  	?asylum_seekers trumpvoc:application_period ?date .
  	?asylum_seekers trumpvoc:application_country ?country .		
    FILTER(regex(str(?nationality), "Soedanees" ) )
  
}order by(?date)
