#+ This query returns groups of asylum seekers who have a specific nationality ( in the specific example Soedanees ). Nationalities have to be in dutch
#+ endpoint: http://stardog.clariah-sdh.eculture.labs.vu.nl/test#!/query
#+ pagination: 100
#+ method: GET

﻿prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

prefix mpo: <http://stardog.clariah-sdh.eculture.labs.vu.nl/databases/the_migration_portal/vocab/>
prefix mpr: <http://stardog.clariah-sdh.eculture.labs.vu.nl/databases/the_migration_portal/resource/>

select distinct ?asylum_seekers ?nationality ?value ?date ?country
where { 
  	          
	graph mpr:asylum_graph{
  	?asylum_seekers mpo:nationality ?nationality .
  	?asylum_seekers mpo:value ?value .
  	?asylum_seekers mpo:application_period ?date .
  	?asylum_seekers mpo:application_country ?country .		
  }
  #Filter to choose nationality
  FILTER(regex(str(?nationality), "Soedanees"))
          
}order by(?date)
