prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX trumpres: <http://localhost:5820/test/resource/>
PREFIX trumpvoc: <http://localhost:5820/test/vocab/>
PREFIX dbo: <http://dbpedia.org/ontology/>

select distinct ?country ?label ?net_migration ?ims ?ert_OECD_percentage ?prp ?prr ?rbcoa ?rbcoo
where { 
  	graph ?g{
	?country a dbo:Country .
    ?country rdfs:label ?label .
	?country trumpvoc:net_migration ?net_migration .
    ?country trumpvoc:international_migrant_stock ?ims .
    ?country trumpvoc:emmigration_rate_to_OECD ?ert_OECD_percentage .
    ?country trumpvoc:personal_remittances_paid ?prp .
    ?country trumpvoc:personal_remittances_received ?prr .
    ?country trumpvoc:refugees_by_country_of_asylum ?rbcoa .
    ?country trumpvoc:refugees_by_country_of_origin ?rbcoo .                
    } 
}
