#+ This query returns groups of asylum seekers and their respected "attributes" filtered by gender and arrival year
#+ endpoint: http://stardog.clariah-sdh.eculture.labs.vu.nl/the_migration_portal#!/query/
#+ pagination: 100
#+ method: GET

﻿prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

prefix mpo: <http://stardog.clariah-sdh.eculture.labs.vu.nl/databases/the_migration_portal/vocab/>
prefix mpr: <http://stardog.clariah-sdh.eculture.labs.vu.nl/databases/the_migration_portal/resource/>
prefix sdmx: <http://purl.org/linked-data/sdmx/2009/code#>
prefix dbr: <http://dbpedia.org/resource/>
prefix dbo: <http://dbpedia.org/ontology/>


select distinct ?asylum_seekers ?nationality ?value ?date ?country ?gender
where { 
  	          
	graph mpr:asylum_graph{
  	?asylum_seekers mpo:nationality ?nationality ;
  				mpo:value ?value ;
    				mpo:application_period ?date ;
  				mpo:application_country ?country ;	
    				mpo:gender ?gender . 
  }
  	#Filter to choose gender & year
	FILTER(?gender =sdmx:sex-F)
	FILTER(regex(str(?date), "2014") || regex(str(?date), "2015")) 

}order by(?date)
