#+ This query returns unemployment data with filters, commenting the filters out return all the data in our unemployment graph 
#+ endpoint: http://stardog.clariah-sdh.eculture.labs.vu.nl/the_migration_portal#!/query/
#+ pagination: 100
#+ method: GET

prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

prefix mpo: <http://stardog.clariah-sdh.eculture.labs.vu.nl/databases/the_migration_portal/vocab/>
prefix mpr: <http://stardog.clariah-sdh.eculture.labs.vu.nl/databases/the_migration_portal/resource/>
prefix sdmx: <http://purl.org/linked-data/sdmx/2009/code#>
prefix dbr: <http://dbpedia.org/resource/>
prefix dbo: <http://dbpedia.org/ontology/>

select distinct ?Country ?Value ?Time_period ?Unit ?Unemployment_rate
where { 
 	graph mpr:unemployment_eu_graph{
      ?Unemployment_rate mpo:country ?Country .
      ?Unemployment_rate mpo:indicator_value ?Value .
      ?Unemployment_rate mpo:time_period ?Time_period .
      ?Unemployment_rate mpo:unit ?Unit .
  	}
  	#FILTER(?Unit = 'Total population')
  	#FILTER((?Unit = 'Active population') && (regex(str(?Country), "Greece" )))

  
}order by(?Time_period)
