prefix mpo: <http://stardog.clariah-sdh.eculture.labs.vu.nl/databases/the_migration_portal/vocab/>
prefix mpr: <http://stardog.clariah-sdh.eculture.labs.vu.nl/databases/the_migration_portal/resource/>
PREFIX sdmx: <http://purl.org/linked-data/sdmx/2009/code#>
prefix dbr: <http://dbpedia.org/resource/>
prefix dbo: <http://dbpedia.org/ontology/>

# Select Countries, with their labels, a time period and the values of their indicators at that timeperiod.
# ValueP = Population Value
# ValueU = Unemployment Value (rate)

select distinct ?Country ?Label ?Time_Period ?ValueTotalP ?ValueForeignP ?ValueU ?From_Country ?To_Country ?InflowValue ?Inflow_Time_Period ?country

where {
    graph mpr:population_eu_graph{
        select ?country ?Time_Period ?ValueForeignP where{
            ?Population mpo:country ?Country ;  
                        mpo:time_period ?Time_Period ;
                        mpo:population_value ?ValueForeignP ;
                        mpo:population_type "Foreign country"^^xsd:string .
            bind(replace(str(?Country), "_\\(.*", "", "i") as ?country) # Germany name fix
        }
    }

    graph mpr:population_eu_graph{
        select ?country ?Time_Period ?ValueTotalP where{
            ?Population mpo:country ?Country ;
                        mpo:time_period ?Time_Period ;
                        mpo:population_value ?ValueTotalP ;
                        mpo:population_type "Total"^^xsd:string .
      bind(replace(str(?Country), "_\\(.*", "", "i") as ?country)
    }
  }
          
#    graph mpr:population_eu_graph{
#    ?Population mpo:country ?Country ;  
#               mpo:time_period ?Time_Period ;
#               mpo:population_value ?ValueTotalF ;
#                mpo:population_type "Foreign country"^^xsd:string .
#    }
                
          
    graph mpr:unemployment_eu_graph{
        ?Unemployment_rate mpo:country ?Country ; 
                           mpo:time_period ?Time_Period ;
                           mpo:unit "Active population"^^xsd:string ;
                           mpo:indicator_value ?ValueU .
        bind(replace(str(?Country), "_\\(.*", "", "i") as ?country)    }
  
    optional{
        graph mpr:inflow_graph{
            ?Inflow mpo:from_country dbr:Total ;
                    mpo:to_country ?To_Country;
                    mpo:movement_time_period ?Inflow_Time_Period ;
                    mpo:movement_value ?InflowValue .    
        filter(str(?To_Country) = ?country) .
        filter(str(?Time_Period) = str(?Inflow_Time_Period))
        
        }
    }
    
# Somewhere here we need to say : if ?Country = ?From_Country make it "country of origin" and To_Country
       
}
order by (?Country) (?Time_Period)
